In [6]:
# Question 1

x <- sample(1:6,10,replace=T)
for (i in x){
    print(x[i])
} 

[1] 2
[1] 4
[1] 6
[1] 3
[1] 3
[1] 4
[1] 6
[1] 3
[1] 3
[1] 3


In [112]:
# Question 2

sample_data <- sample(1:6,10,replace=T)
print(sample_data)

sample_space <- matrix(0, nrow=6, ncol=6)

for (ind in 2:length(sample_data)-1) {
    curEle <- sample_data[ind]
    nexEle <- sample_data[ind+1]
    sample_space[[curEle,nexEle]] = sample_space[[curEle,nexEle]] + 1
}
print(sample_space)

 [1] 5 4 4 4 2 4 5 3 4 4
     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    0    0    0    0    0    0
[2,]    0    0    0    1    0    0
[3,]    0    0    0    1    0    0
[4,]    0    1    0    3    1    0
[5,]    0    0    1    1    0    0
[6,]    0    0    0    0    0    0


In [131]:
# Question 3

sample_data <- sample(1:6,5000,replace=T)
sample_space <- matrix(0, nrow=6, ncol=6)

for (ind in 2:length(sample_data)-1) {
    curEle <- sample_data[ind]
    nexEle <- sample_data[ind+1]
    sample_space[[curEle,nexEle]] = sample_space[[curEle,nexEle]] + 1
}

sample_space_prob <- matrix(0, nrow=6, ncol=6)
for (sample_index in 1:6) {
    element_count <- 0
    for (eleIndex in 1:6) {
        element_count = element_count + sample_space[[sample_index, eleIndex]]
    }
    for (sample_number in 1:6) {
        sample_space_prob[[sample_index, sample_number]] = sample_space[[sample_index, sample_number]] / element_count

    }       
}

# print("### Sample Data ###")
# print(sample_data)
print("### Sample Space ###")
print(sample_space)
print("### Sample Space Probablity ###")
print(sample_space_prob)

[1] "### Sample Space ###"
     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]  128  127  126  142  135  149
[2,]  138  154  122  145  152  137
[3,]  128  129  146  146  148  132
[4,]  131  138  131  160  155  129
[5,]  133  149  168  120  144  139
[6,]  149  150  136  131  120  132
[1] "### Sample Space Probablity ###"
          [,1]      [,2]      [,3]      [,4]      [,5]      [,6]
[1,] 0.1586121 0.1573730 0.1561338 0.1759603 0.1672862 0.1846344
[2,] 0.1627358 0.1816038 0.1438679 0.1709906 0.1792453 0.1615566
[3,] 0.1544029 0.1556092 0.1761158 0.1761158 0.1785283 0.1592280
[4,] 0.1552133 0.1635071 0.1552133 0.1895735 0.1836493 0.1528436
[5,] 0.1559203 0.1746776 0.1969519 0.1406800 0.1688159 0.1629543
[6,] 0.1821516 0.1833741 0.1662592 0.1601467 0.1466993 0.1613692
